class ResError(Exception):
    pass  # this just creates an error that we can use